--- Cargo.toml.orig	2025-01-01 00:00:00 UTC
+++ Cargo.toml
@@ -1,4 +1,13 @@
 [workspace]
+
+[workspace.package]
+# Required metadata for third-party crates that inherit workspace fields
+# (e.g., neqo sub-crates that use authors.workspace = true)
+authors = ["Mozilla Contributors"]
+edition = "2021"
+license = "MPL-2.0"
+repository = "https://github.com/mozilla/gecko-dev"
+
 members = [
     "browser/app/nmhproxy",
     "browser/locales_preview/nickel",
